version: 2

models:
  - name: first
    description: "First dbt model"
    columns:
        - name: id
          description: "The primary key for this table"
          tests:
              - unique
              - not_null

  - name: second
    description: "Second dbt model"
    columns:
        - name: id
          description: "The primary key for this table"
          tests:
              - unique
              - not_null
